name: LINUX

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  linux-native:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-mobagen
          path: |
            /home/runner/.hunter
            /home/runner/work/mobagen/mobagen/external/emsdk/zips/

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential cmake mesa-common-dev libgl1-mesa-dev libx11-dev mesa-common-dev mesa-utils libgl-dev python3-distutils libgl1-mesa-dev libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev  

      - name: Configure CMake
        run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_EDITOR=ON

      - name: Build
        run: cmake --build build/ --parallel

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}