name: OSX

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  osx-native:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.hunter
          key: ${{ runner.os }}-mobagen

      - name: Configure CMake
        run: cmake -Bbuild -H. -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_EDITOR=ON

      - name: Build
        run: cmake --build build/ --parallel

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}