name: WINDOWS

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  BUILD_TYPE: MinSizeRel

jobs:
  windows-native:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: cache
        uses: actions/cache@v3
        with:
          path: /home/runner/.hunter
          key: ${{ runner.os }}-mobagen

      - name: Configure CMake
        shell: cmd
        run: cmake -H. -Bbuild -G "Visual Studio 17 2022" -T ClangCL -DCMAKE_BUILD_TYPE=MinSizeRel -DBUILD_EDITOR=ON

      - name: Build
        shell: cmd
        run: cmake --build build --config MinSizeRel --parallel

      - name: Release
        uses: fnkr/github-action-ghr@v1.3
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GHR_COMPRESS: zip
          GHR_PATH: build/
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}